baseURL = "https://Xiaotong713986.github.io"
theme = "hugo-research-team"
publishDir = "docs"
languageCode = "en"
title = "FMC-IML-Lab"
paginate = 7
mainSections = "post"
personSections = "person"
Teacher = "teacher"
# languageCode = "zh-cn"
# title = "武斌的博客"
# theme = "hugo-cxy-theme"
# preserveTaxonomyNames = true
# paginate = 10 #frontpage pagination
# hasCJKLanguage = true
# custom_css = ["/css/custom.css"]
# custom_js = []

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 1

[[menu.main]]
    name = "Group"
    url = "/group/"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "/pub/"
    weight = 3

# [outputs]
# home = ["HTML", "RSS"]

[params]
avatar = "/person/XuWang.jpg" 
# hero_bg = "/images/header-bg.jpg"
SEOTitle = "FMC"
description = "课题组介绍 | 这里是FMC-IML 课题组的介绍。"
# keyword = "wubin1989, wubin1989, wubin1989的网络日志, wubin1989的博客, wubin1989 Blog, 博客, 个人网站, 互联网, Web, Nodejs, Reactjs, SaaS, Golang, 微服务, Microservice"

# image_404 = "/images/404-bg.jpg"
# title_404 = "你来到了没有知识的荒原 :("

[taxonomies]
tag = "tags"
category = "categories"
archive = "archives"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
