baseURL = "https://Xiaotong713986.github.io"
theme = "hugo-research-team"
publishDir = "docs"
languageCode = "en"
title = "FMC-IML-Lab"
paginate = 7
mainSections = "post"
personSections = "person"
Teacher = "teacher"
# languageCode = "zh-cn"

[[menu.main]]
	name = "中文版"
	url = "/ch"
    weight = 1

[[menu.main]]
	name = "Home"
	url = "/"
    weight = 2

[[menu.main]]
    name = "Group"
    url = "/group/"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "/pub/"
    weight = 4

[[menu.ch]]
	name = "En"
	url = "/"
    weight = 1

[[menu.ch]]
	name = "主页"
	url = "/ch/"
    weight = 2

[[menu.ch]]
    name = "组员"
    url = "/group-ch/"
    weight = 3

[[menu.ch]]
    name = "论文"
    url = "/pub/"
    weight = 4

# [outputs]
# home = ["HTML", "RSS"]

[params]
avatar = "/person/XuWang.jpg" 
SEOTitle = "FMC"
description = "课题组介绍 | 这里是FMC-IML 课题组的介绍。"

[taxonomies]
tag = "tags"
category = "categories"
archive = "archives"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
